### ISSUE TITLE
Site Not Live

### ISSUE THREAD

**Issue by MusaAqeel** [Tolujoh-n/study-online#1]
As a judge for the Maple-X-Tommy Hacks event, I wanted to bring to your attention that the site for your submission does not appear to be live at the moment. Could you please fix this issue as soon as possible? Thank you for your cooperation.

Musa Aqeel

**Comment by Tolujoh-n** [comment]
Have checked the link sir but I couldn’t find out where the problem is coming from sir. Here is my project GitHub repository link sir 

https://github.rcom/Tolujoh-n/study-online

This link is live sir and this is the link I also submitted at devpost.com sir. 

And have also submitted my project zip file at devpost sir 
I tried hosting it but am finding it difficult sir am sorry for that.

**Comment by Tolujoh-n** [comment]
Am working on it sir

**Comment by Tolujoh-n** [comment]
> As a judge for the Maple-X-Tommy Hacks event, I wanted to bring to your attention that the site for your submission does not appear to be live at the moment. Could you please fix this issue as soon as possible? Thank you for your cooperation.
> 
> Musa Aqeel

Have hosted the site sir. It’s known live, have provided the link on devpost.com

**Comment by MusaAqeel** [comment]
Looks good, thanks!
